AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 30

Resources:
  CloudWatchSNSToSlackLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: cloudwatch-sns-to-slack
      CodeUri: ./bin/ 
      Runtime: go1.x
      MemorySize: 128
      Environment:
        Variables:
          WEBHOOK_URL: "replace_with_your_webhook_url"
          